language: php

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
        - TASK_STATIC_ANALYSIS=0
        - TASK_TESTS_COVERAGE=0

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        -   php: "7.2"
            env:
                - TASK_TESTS_COVERAGE=1
        -   php: "7.3"
            env:
                - TASK_STATIC_ANALYSIS=1
        -   php: "7.4snapshot"

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
    - travis_retry composer self-update
    - travis_retry composer global require hirak/prestissimo
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
    - pecl install ast

before_script:
    # show some versions and env information
    - php --version
    - composer --version
    # enable code coverage
    - |
        if [ $TASK_TESTS_COVERAGE == 1 ]; then
            PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
        fi

script:
    - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
    - |
        if [ $TASK_STATIC_ANALYSIS == 1 ]; then
          composer phan
        fi
    - |
        if [ $TASK_STATIC_ANALYSIS == 1 ]; then
          cat analysis.txt
        fi

after_script:
    - |
        if [ $TASK_TESTS_COVERAGE == 1 ]; then
          travis_retry wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi

notifications:
  slack:
    -
      rooms:
        -
          secure: O7W0xr19V0K5UXqrsq2hPEwUKkPvmB5VdSXm6e/3kWMD/UPss0RLtEEPyFn/7wl9SVhRCuJ7hhSTRNm2T/hwhnSjYSlwfeMx1r9oh0zo5wZnPuhZ3/nGNLG097CkvRgxuL/httd/2PDgcSv4GIuI7QXbQIl5Lc1vZZSaSAMac2J0SOzPjK+87GcVIB9gE4yeHQoMnfPo0Q8aDj7QCt+pGz8h5X+9NUEPQjfHZ/2G+XmwjKZhXa14ucSLp7xnU5exjHbdhTifHxC2LXIVRgoaia85BFXZqy/QoTX6waX/xxoUQjHZ1hjGn0X1PcHkxUPQt/xJm2FIkZ66MIk2JigZIdYF1YCWeOspOn4Js4xdlqYz0m6kSArgxVHUCtnMmwhPb8lmPenI5pJizup4sS1t3iau6iwlf6iirKGQWpekfEYbCgeIIoge3NYbuz8r9ZV90GjSUJvzRsVqOILt/FZFNRNbxsj0KphZU7Ig1ILt0/zU73TJ2hZAQBcN+X5yuM2hPhMCTgH7HEVb25l3u/09ta8sImX3s33OUaLzMnwRVickM8CEcm4c4KDACq2OvYKLbVJliLLkgZ35peFnq8Rj3iXipGCVIHKn4PI8YQxA4qvrRduHtPAfARDrHXUjkPKd7h6DiqeDrTGw4AUHqEMhOkFYgqEbCyNDGXxjUbqQj1o=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: Pk1MEoDK4gZLWui46yVh3Nce5NmD3t+L5F113KBNnBa4ekOiJ6MvIeiplka2gCGTklZS77uZ0z727UB95m6mkiLC/mToUgJgrBX72LJRxwBDKziVQGW5xCyiyfv026Y3qXjzchRjwq/hbusSUom29TiLbLSuCApZVxq05gOhe1wb2fcdhOYsDcrYMTfbv1N72wWNpD7R0vt9xw6+FeEKYmCqrPyRoo6Q8whikduQN30FE7ktCqYS0Yx/0AU3DFIWX+6KFw5p7lziLJcrn1NT+5eX7P4dxQro+Lgp7VY9PhhN2pjF+KGwLVC9VVC1QkKdCcxlq+pXjHijO+ClgvM4Wr/lEivcGRSkR5zu8s9jklxp9kgqgfcTY+OGuAynQwtjfZbc8ujES0z8NbLUSrCntb91C8pdTU/i605iweqFPf7f5nCoYP76XWQ/T0JM+G2nY842/I4O2BNl1tup5wMm+KPc3jFJkdwxn1vp0hLn5kPTMX5FsvfY0JQ97RZrO/TBGPAT1rxEdOW7DjUYxNBZr2iTMtBUPE+3fldy3Ug6bIotXvlQ7GxytAFIAx1RViEOZxlMi6GSFizkgRPRYv22SzaOiHXxF2S0WIoPocYUB7bavSQqKEqWMgWSBpmbQhp+IXDVOs8KITJ2VnV4IbH8r9bhUzkWuAtkIkC9W7FTbdM=
      on_success: never
      on_failure: always
      on_pull_requests: false
